/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Lock__factory } from "./Lock__factory";
export { Web3Voting__factory } from "./Web3Voting__factory";
